### ISSUE TITLE
metadata for "Get image urls of a list of species"

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylo_services_docs#8]
Users may request image URLs for a list of species.  It is useful to know where the images came from, and any rights associated with them.  This information can be copied from the EOL sources.  

Provide metadata for a list of image URLs, to include 
* timestamp
* number of names in query 
* number of thumbnail URLs returned
* URL of service 
* URL of documentation for service 
* for each thumbnail image URL (eolThumbnailURL)
   * the taxon name (EOL "scientificName")
   * the EOL taxon id (EOL "identifier")
   * "mimeType"
   * "license"
   * "rightsHolder "
   * "eolMediaURL" (the URL for the full-size image)

**Comment by arlin** [comment]
Good.  Same issue as for #6 and others.  Please remove comments and put query string in json.

**Comment by abusalehmdtayeen** [comment]
Done.

**Comment by arlin** [comment]
I'm still seeing the comments.  `// original-url-string` is not valid json.  Most parsers ignore it but we should not put it in a stream and label it "json" if it isn't json.   This is valid json: 
`{
        "//" : "original-url-string"
}`
but the original url is metadata, not comment, so it may as well be 
`{
        "the original url" : "original-url-string"
}`

Right?  

<img width="454" alt="screen shot 2017-03-16 at 12 18 46 pm" src="https://cloud.githubusercontent.com/assets/1659198/24007014/c9285e06-0a43-11e7-90cb-94e6297a3d0c.png">

**Comment by abusalehmdtayeen** [comment]
@arlin , I don't see any comments when I use Mozilla browser.  The result returned is a valid json which I checked with a browser plugin. Can you please check with another browser? May be its browser specific on Mac.
